### ISSUE TITLE
NativeLibResolver::loadNativeLib failes to check Java library paths

### ISSUE THREAD

**Issue by marvk** [aploese/jnhw#1]
https://github.com/aploese/jnhw/blob/e30aead64db4de1f3adab16b249fd7a266b55f1c/de.ibapl.jnhw.libloader/src/main/java/de/ibapl/jnhw/libloader/NativeLibResolver.java#L205

Here, the elements in `java.library.path` are split at every colon (`:`). However, at least on my machine running Windows 10, the elements in `java.library.path` separated by a semicolon (`;`). This leads `loadNativeLib` to consider paths like `\Program Files\AdoptOpenJDK\jdk-11.0.5.10-hotspot\bin;C` instead of `C:\Program Files\AdoptOpenJDK\jdk-11.0.5.10-hotspot\bin` for library loading.

I don't know if elements are separated by colons on other operating systems.

**Comment by aploese** [comment]
Unix(POSIX?) uses colons win uses semicolons ... 
fixed in master
