### ISSUE TITLE
Ioapiset is incomplete

### ISSUE THREAD

**Issue by marvk** [aploese/jnhw#2]
`ioapiset.h` in Windows SDK version 10.0.18362.0 includes methods that are not included in [`Ioapiset`](https://github.com/aploese/jnhw/blob/f638b8f5e77941f6126ffc39290a7e9d310c17ef/de.ibapl.jnhw.winapi/src/main/java/de/ibapl/jnhw/winapi/Ioapiset.java#L43). I, for example, require `DeviceIoControl`. Including this missing method would be really useful.

**Comment by aploese** [comment]
I only implemented functions that I'm currently use and there for have testcases for it. 

The easiest way is to fork, add the native stub to the java side, add a test case. That is the essential part.
You can also implement the native side and compile it - or ask for it. 
Then submit a pull request.

**Comment by aploese** [comment]
Fixed in master
