### ISSUE TITLE
README has wrong maven artifact for Windows API

### ISSUE THREAD

**Issue by marvk** [aploese/jnhw#3]
The [README](https://github.com/aploese/jnhw/blob/master/README.md) mentions [`de.ibapl.jnhw.posix`](https://mvnrepository.com/artifact/de.ibapl.jnhw/de.ibapl.jnhw.posix) for the Windows API when, in fact, it should be [`de.ibapl.jnhw.winapi`](https://mvnrepository.com/artifact/de.ibapl.jnhw/de.ibapl.jnhw.winapi).

This seems to be a copy paste error.

**Comment by aploese** [comment]
fixed in master
